---
- name: Restart exporter service
  systemd:
    name: edgelink-monitor.service
    state: restarted
    daemon_reload: yes
    enabled: yes
- name: Restart WireGuard
  service:
    name: wg-quick@wg0
    state: restarted